- include_tasks: check_subscriber.yml

- include_tasks: delete_subscriber.yml
  with_items: "{{ check_cygnus_mongo_subscriber_result.json }}"
  loop_control:
    loop_var: subscriber
  when: check_cygnus_mongo_subscriber_result.json | length | int > 0

- include_tasks: register_cygnus_mongo_subscriber.yml

- include_tasks: check_subscriber.yml

- debug:
    msg: "{{ check_cygnus_mongo_subscriber_result.json }}"
