- name: check devices
  uri:
    url: "{{ url.idas.devices }}"
    method: GET
    headers:
      Authorization: "bearer {{ tokens[0] }}"
      Fiware-Service: "{{ fiware.service }}"
      Fiware-ServicePath: "{{ _service_path }}"
  register: check_device_register_result
