- name: delete device
  uri:
    url: "{{ url.idas.devices }}{{ devices.device_id }}"
    method: DELETE
    status_code: 204
    headers:
      Authorization: "bearer {{ tokens[0] }}"
      Fiware-Service: "{{ fiware.service }}"
      Fiware-ServicePath: "{{ _service_path }}"
