- name: delete service
  uri:
    url: "{{ url.idas.services }}?resource={{ services.resource }}&apikey={{ services.apikey }}"
    method: DELETE
    status_code: 204
    headers:
      Authorization: "bearer {{ tokens[0] }}"
      Fiware-Service: "{{ fiware.service }}"
      Fiware-ServicePath: "{{ _service_path }}"
