- import_tasks: _register_users_to_rabbitmq.yml
#- import_tasks: _register_delivery_robot_service.yml
#- import_tasks: _register_delivery_robot_devices.yml
#- import_tasks: _register_cygnus_mongo_subscriber.yml
#- import_tasks: _register_robotui_service.yml
