- name: register delivery robot device
  uri:
    url: http://localhost:8080/idas/json/manage/iot/devices/
    method: POST
    body_format: json
    status_code: 201
    headers:
      Authorization: "bearer {{ tokens[0] }}"
      Fiware-Service: "{{ fiware.service }}"
      Fiware-ServicePath: "{{ fiware.delivery_robot.service_path }}"
    body: "{{ lookup('template','register_delivery_robot_device.json.j2') }}"
