- debug:
    msg: "{{ lookup('template', 'mqtt_payload.json.j2') }}"

- name: get date to iso format
  iso8601:
  register: date

- name: send mqtt message
  mqtt:
    topic: "/delivery_robot/{{ _id }}/cmd"
    #topic: "/delivery_robot/delivery_robot_01/cmd"
#    ca_cert:
    username: "{{ mqtt.users[0].name }}"
    password:  "{{ mqtt.users[0].password }}"
#    payload: "{{ lookup('template', 'mqtt_payload.json.j2') }}"
    payload: "{\"send_cmd\":{\"time\":\"1970-01-01T09:00:00+09:00\",\"cmd\":\"navi\",\"waypoints\":[{\"point\":{\"x\":-0.1,\"y\":0.5,\"z\":0},\"angle\":{\"roll\":0,\"pitch\":0,\"yaw\":-1.57}}]}}"
    qos: 0
    port: 1883
  delegate_to: localhost
- name: confirm
  pause: prompt="Press Enter key when the robot is reached."
