apiVersion: v1
kind: Service
metadata:
  name: robotui
  labels:
    app: robotui
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  robotui-mapping
      prefix: /
      host: "^robotui\\..+$"
      host_regex: true
      service: http://robotui:8080
spec:
  type: ClusterIP
  selector:
    app: robotui
  ports:
  - name: robotui
    port: 8080
    targetPort: 80
