- name: delete core auth-token secret
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: auth-tokens
        namespace: default

- name: check to delete auth-token secret
  k8s_info:
    kind: Secret
    name: auth-tokens
    namespace: default
  register: auth_tokens_secret_result
  until: auth_tokens_secret_result.resources | length == 0
  retries: 6
  delay: 10
