apiVersion: v1
kind: Service
metadata:
  name: robot-controller
  labels:
    app: robot-controller
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  controller-mapping
      prefix: /controller/
      host: "^api\\..+$"
      host_regex: true
      service: http://robot-controller:3000
spec:
  type: ClusterIP
  selector:
    app: robot-controller
  ports:
  - name: r-controller
    port: 3000
    targetPort: 3000
